server:
  port: 9070
  max-http-header-size: 756000
  jetty:
    threads:
      min: 100
      max: 3000
      idle-timeout: 10000
    connection-idle-timeout: 10000
    accesslog:
      append: true

spring:
  application:
    name: multiplication-service
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/multiplication;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 15
      max-lifetime: 10000
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

service:
  api:
    base-path: /services/multiplication
  openapi:
    version: 'version1.0.1 1401/05/03'
    title: 'multiplication-service'
    description: 'multiplication-service'

springdoc:
  swagger-ui:
    display-operation-id: true
    display-request-duration: true
    path: /swagger-ui.html

  api-docs:
    path: /v3/multiplication/api-docs


management:
  endpoints:
    web:
      base-path: /actuators/multiplication
      exposure:
        include: '*'
